server:
  port: 9443
spring:
  application:
    name: api
  data:
    mongodb:
     authentication-database: admin
     database: web_store
     port: 27017
     host: localhost
     username: root
     password: example
     auto-index-creation: true
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url: 
      defaultZone: http://localhost:9440/eureka/
    register-with-eureka: true  
